spring:
  kafka:
    producer:
      bootstrap-servers: my-kafka:9092
      acks: all
    consumer:
      bootstrap-servers: my-kafka:9092
    listener:
      ack-mode: manual_immediate
      type: single